// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/s7r8/reviewapp/internal/application/usecase/knowledge"
	"github.com/s7r8/reviewapp/internal/application/usecase/review"
	"github.com/s7r8/reviewapp/internal/domain/service"
	"github.com/s7r8/reviewapp/internal/infrastructure/config"
	"github.com/s7r8/reviewapp/internal/infrastructure/external"
	"github.com/s7r8/reviewapp/internal/infrastructure/persistence/postgres"
	"github.com/s7r8/reviewapp/internal/interfaces/http/handler"
)

// Injectors from wire.go:

// InitializeKnowledgeHandler - KnowledgeHandlerを初期化（Wireが自動生成）
func InitializeKnowledgeHandler(db *sql.DB) (*handler.KnowledgeHandler, error) {
	knowledgeRepository := postgres.NewKnowledgeRepository(db)
	createKnowledgeUseCase := knowledge.NewCreateKnowledgeUseCase(knowledgeRepository)
	listKnowledgeUseCase := knowledge.NewListKnowledgeUseCase(knowledgeRepository)
	knowledgeHandler := handler.NewKnowledgeHandler(createKnowledgeUseCase, listKnowledgeUseCase)
	return knowledgeHandler, nil
}

// InitializeReviewHandler - ReviewHandlerを初期化（Wireが自動生成）
func InitializeReviewHandler(db *sql.DB, cfg *config.Config) (*handler.ReviewHandler, error) {
	reviewRepository := postgres.NewReviewRepository(db)
	knowledgeRepository := postgres.NewKnowledgeRepository(db)
	reviewService := service.NewReviewService()
	claudeClient := ProvideClaudeClient(cfg)
	reviewCodeUseCase := review.NewReviewCodeUseCase(reviewRepository, knowledgeRepository, reviewService, claudeClient)
	updateFeedbackUseCase := review.NewUpdateFeedbackUseCase(reviewRepository)
	reviewHandler := handler.NewReviewHandler(reviewCodeUseCase, updateFeedbackUseCase)
	return reviewHandler, nil
}

// wire.go:

// ProvideClaudeClient - ClaudeClientのプロバイダ
func ProvideClaudeClient(cfg *config.Config) *external.ClaudeClient {
	return external.NewClaudeClient(
		cfg.LLM.ClaudeAPIKey,
		cfg.LLM.ClaudeModel,
		cfg.LLM.ClaudeMaxTokens,
	)
}
