// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/s7r8/reviewapp/internal/application/usecase/dashboard"
	"github.com/s7r8/reviewapp/internal/application/usecase/knowledge"
	"github.com/s7r8/reviewapp/internal/application/usecase/review"
	"github.com/s7r8/reviewapp/internal/domain/service"
	"github.com/s7r8/reviewapp/internal/infrastructure/config"
	"github.com/s7r8/reviewapp/internal/infrastructure/external"
	"github.com/s7r8/reviewapp/internal/infrastructure/persistence/postgres"
	"github.com/s7r8/reviewapp/internal/interfaces/http/handler"
)

// Injectors from wire.go:

// InitializeKnowledgeHandler - KnowledgeHandlerを初期化（Wireが自動生成）
func InitializeKnowledgeHandler(db *sql.DB, cfg *config.Config) (*handler.KnowledgeHandler, error) {
	knowledgeRepository := postgres.NewKnowledgeRepository(db)
	openAIClient := ProvideOpenAIClient(cfg)
	createKnowledgeUseCase := knowledge.NewCreateKnowledgeUseCase(knowledgeRepository, openAIClient)
	updateKnowledgeUseCase := knowledge.NewUpdateKnowledgeUseCase(knowledgeRepository, openAIClient)
	listKnowledgeUseCase := knowledge.NewListKnowledgeUseCase(knowledgeRepository)
	deleteKnowledgeUseCase := knowledge.NewDeleteKnowledgeUseCase(knowledgeRepository)
	knowledgeHandler := handler.NewKnowledgeHandler(createKnowledgeUseCase, updateKnowledgeUseCase, listKnowledgeUseCase, deleteKnowledgeUseCase)
	return knowledgeHandler, nil
}

// InitializeReviewHandler - ReviewHandlerを初期化（Wireが自動生成）
func InitializeReviewHandler(db *sql.DB, cfg *config.Config) (*handler.ReviewHandler, error) {
	reviewRepository := postgres.NewReviewRepository(db)
	knowledgeRepository := postgres.NewKnowledgeRepository(db)
	reviewService := service.NewReviewService()
	claudeClient := ProvideClaudeClient(cfg)
	openAIClient := ProvideOpenAIClient(cfg)
	reviewCodeUseCase := review.NewReviewCodeUseCase(reviewRepository, knowledgeRepository, reviewService, claudeClient, openAIClient)
	updateFeedbackUseCase := review.NewUpdateFeedbackUseCase(reviewRepository)
	listReviewsUseCase := review.NewListReviewsUseCase(reviewRepository)
	getReviewUseCase := review.NewGetReviewUseCase(reviewRepository)
	reviewHandler := handler.NewReviewHandler(reviewCodeUseCase, updateFeedbackUseCase, listReviewsUseCase, getReviewUseCase)
	return reviewHandler, nil
}

// InitializeDashboardHandler - DashboardHandlerを初期化（Wireが自動生成）
func InitializeDashboardHandler(db *sql.DB) (*handler.DashboardHandler, error) {
	reviewRepository := postgres.NewReviewRepository(db)
	knowledgeRepository := postgres.NewKnowledgeRepository(db)
	getStatsUseCase := dashboard.NewGetStatsUseCase(reviewRepository, knowledgeRepository)
	dashboardHandler := handler.NewDashboardHandler(getStatsUseCase)
	return dashboardHandler, nil
}

// wire.go:

// ProvideClaudeClient - ClaudeClientのプロバイダ
func ProvideClaudeClient(cfg *config.Config) *external.ClaudeClient {
	return external.NewClaudeClient(
		cfg.LLM.ClaudeAPIKey,
		cfg.LLM.ClaudeModel,
		cfg.LLM.ClaudeMaxTokens,
	)
}

// ProvideOpenAIClient - OpenAIClientのプロバイダ
func ProvideOpenAIClient(cfg *config.Config) *external.OpenAIClient {
	return external.NewOpenAIClient(
		cfg.LLM.OpenAIAPIKey,
		cfg.LLM.OpenAIEmbedding,
		cfg.LLM.OpenAITimeout,
	)
}
